import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Two explicit sidebars rather than one autogenerated tree.
 *
 * ADRs are the part of this site people are sent to ("read ADR-006 before changing
 * the CSP"), so they get their own top-level section in decision order — not
 * alphabetical, and not buried under a generic "docs" heading. Reference material is
 * the planning and requirements corpus, which is browsed rather than navigated.
 *
 * The task recipes deliberately live in `.claude/skills/` and are NOT duplicated
 * here. A recipe copied into two places drifts, and the copy that drifts is always
 * the one somebody follows. This site links to them instead.
 */
const sidebars: SidebarsConfig = {
  // Docusaurus strips the numeric filename prefix when deriving a doc id
  // (`001-rendering-strategy.md` → `adr/rendering-strategy`), so these are the ids
  // rather than the filenames. The prefix still lives on disk, which is what keeps the
  // ADRs in decision order in a directory listing and in `git log`.
  adr: [
    "index",
    "adr/README",
    "adr/rendering-strategy",
    "adr/ui-base",
    "adr/redis-cache-handler",
    "adr/editorial-workflow-on-ce",
    "adr/monorepo-ci-change-detection",
    "adr/security-hardening",
    "adr/csp-without-nonces",
  ],
  reference: [
    "index",
    "architecture_plan",
    "master_summary",
    "website-req_details",
    "web-mng_details",
    "web-tracking_details",
    "phase_guide",
    "p3-freshness",
    "init",
  ],
};

export default sidebars;
